name: Sync LeetCode CN

on:
  workflow_dispatch:      # 允许手动触发
  schedule:
    - cron: "0 8 * * *"   # 每天北京时间 16:00 自动同步

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        # 核心修改：使用支持国区的 zanjs 分支版本
        uses: zanjs/leetcode-sync@HEAD  
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          host: cn  # 关键参数：指定同步国区 leetcode.cn
          destination-folder: .
          verbose: true
