name: Sync LeetCode

on:
  workflow_dispatch:  # 允许你在 Actions 页面手动点击按钮触发同步
  schedule:
    - cron: "0 8 * * *"  # 每天北京时间下午4点自动同步 (UTC时间08:00)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-base-url: 'https://leetcode.cn'
          destination-folder: . # 同步到仓库根目录
          verbose: true # 在日志中显示详细信息
          commit-header: '[LeetCode Sync]' # 提交信息的统一前缀
